# Generated by Django 5.1.6 on 2025-02-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_field', models.IntegerField(blank=True, null=True)),
                ('text_field', models.CharField(blank=True, max_length=255, null=True)),
                ('date_field', models.DateField(blank=True, null=True)),
                ('is_number_checked', models.BooleanField(default=False)),
                ('is_text_checked', models.BooleanField(default=False)),
                ('is_date_checked', models.BooleanField(default=False)),
            ],
        ),
    ]
